CryptoTrade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cryptoApp.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cryptoApp/urls.py
from django.urls import path
from cryptoApp import views
from django.contrib.auth import views as auth_views
from cryptoApp.article_views import (
  ArticleCreateView, ArticleListView, ArticleDetailView
)

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.custom_login, name='login'),
    path('logout/', views.logout_view, name='logout_view'),
    path('index/', views.index, name='index'),
    path('coin/<int:coin_id>', views.coin_detail, name='coin_detail'),
    path('converter/', views.converter, name='converter'),
    path('transaction/', views.user_transactions, name='user_transactions'),
    path('wallet/<int:coin_id>/', views.wallet_view, name='wallet_view'),
    path('sell_transaction/<int:transaction_id>/', views.sell_transaction, name='sell_transaction'),
    path('success/', views.success_view, name='success_view'),
    path('failure/', views.insufficient_balance_view, name='insufficient_balance_view'),
    path('submit_exchange/', views.add_currency, name='submit_exchange'),
    path('submit_crypto/', views.add_coin, name='submit_crypto'),
    path(
      'articles/create/', ArticleCreateView.as_view(),
      name='article_create'
    ),
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path(
      'articles/<int:pk>/', ArticleDetailView.as_view(),
      name='article_detail'
    ),
    path('s_home/',views.s_home, name="s_home"),
    path('profile_list/', views.profile_list, name='profile_list'),
    path('profile/<int:pk>', views.profile, name='profile' ),
    path('update_user/', views.update_user, name='update_user' ),
    path('beet_like/<int:pk>', views.beet_like, name='beet_like' ),
    path('delete_beet/<int:pk>', views.delete_beet, name='delete_beet' ),
    path('search/', views.search, name='search' ),
    path('watchlist/', views.watchlist, name='watchlist'),
    path('add_to_watchlist/<int:coin_id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('remove_from_watchlist/<int:coin_id>/', views.remove_from_watchlist, name='remove_from_watchlist'),


]

cryptoApp/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User, AbstractUser, Group, Permission
from django.conf import settings
from django.db.models.signals import post_save
User = settings.AUTH_USER_MODEL
from django.contrib.auth import get_user_model
from django.conf import settings
from django.utils import timezone
User = settings.AUTH_USER_MODEL
from django.db.models.signals import post_save


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    id_or_photo = models.FileField(upload_to='id_photos/', null=True, blank=True)
    groups = models.ManyToManyField(Group, related_name='customuser_set', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_set', blank=True)
    createdDate = models.DateTimeField(auto_now_add=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=500.00)

class Watchlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    coins = models.ManyToManyField('Coin')
    def __str__(self):
        coin_names = ', '.join([coin.name for coin in self.coins.all()])
        return f"{self.user.username}'s Watchlist - {coin_names}"
class Coin(models.Model):
    name = models.CharField(max_length=250, null=True)
    symbol = models.CharField(max_length=10, null=True)
    price = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    percentage_change_1h = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    percentage_change_24h = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    percentage_change_7d = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    market_cap = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    all_time_high = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    graph_link = models.URLField(blank=True)
    icon_url = models.URLField(blank=True)
    createdDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"


class Currency(models.Model):
    code = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.code


class CurrencyConverter(models.Model):
    coin = models.ForeignKey(Coin, on_delete=models.CASCADE)
    amount = models.FloatField()
    currency = models.CharField(max_length=3)
    result = models.FloatField()
    is_coin_to_currency = models.BooleanField()

    def __str__(self):
        return f"{self.amount} {self.coin.symbol} to {self.currency}"



class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Transaction(models.Model):
    TRANSACTION_TYPES = (
        ('buy', 'Buy'),
        ('sell', 'Sell'),
    )

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    order = models.ForeignKey(Coin, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    transaction_type = models.CharField(max_length=4, choices=TRANSACTION_TYPES)
    balance_after_transaction = models.DecimalField(max_digits=10, decimal_places=2)
    sold = models.BooleanField(default=False)



class Profile(models.Model):
    objects = None
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField("self",
                                     related_name="followed_by",
                                     symmetrical=False,
                                     blank=True)
    date_modified = models.DateTimeField(User,auto_now=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to="images/")

    def __str__(self):
        return self.user.username


# creating a profile when new users signup
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)  # creating a profile automatically for every user that gets created
        user_profile.save()
        # user follow themselves
        user_profile.follows.set([instance.profile.id])  # I am getting the id from the migrations file
        user_profile.save()  # we save twice because first we have to save the profile that was created and the
        # second time when they are followed


post_save.connect(create_profile, sender=User)  # when a new user has been saved we will create a new profile


class Beet(models.Model):
    user = models.ForeignKey(
        User, related_name="beets",
        on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=200)
    created_at=models.DateTimeField(auto_now_add=True)
    likes= models.ManyToManyField(User, related_name="beet_like", blank=True)

    #counting likes
    def number_of_likes(self):
        return self.likes.count()

    def __str__(self):
        return( f"{self.user} "
                f"({self.created_at:%Y/%m/%d %H:%M}): "
                f"{self.body}..."
                )

cryptoApp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import CustomUser, Coin, Currency, Article, Beet, Profile
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from datetime import date
class SignUpForm(UserCreationForm):
    name = forms.CharField(max_length=255, label='Name')
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'id_or_photo']

    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput,
        error_messages={},
    )

    username = forms.CharField(
        max_length=150,
        error_messages={
            'unique': "A user with that username already exists.",
            'invalid': "Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.",
            'required': "This field is required.",
        },
    )
    email = forms.EmailField(
        max_length=255,
        error_messages={
            'invalid': "Enter a valid email address.",
            'required': "This field is required.",
        },
    )

    id_or_photo = forms.ImageField(
        required=True,
        error_messages={
            'required': "This field is required.",
        },
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        User = get_user_model()
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already in use. Please choose a different one.")
        return username

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.first_name = self.cleaned_data['name']
        if commit:
            user.save()
        return user

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['password2'].widget = forms.HiddenInput()
        self.fields.pop('password2', None)


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password')


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content']


class ConverterForm(forms.Form):
    amount = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-input',
                                                              'placeholder': 'Enter Amount to Convert'}))
    coin_type = forms.ModelChoiceField(queryset=Coin.objects.all(), empty_label=None,
                                       widget=forms.Select(attrs={'class': 'form-select'}))
    currency = forms.ModelChoiceField(queryset=Currency.objects.all(),
                                      initial='USD',
                                      widget=forms.Select(attrs={'class': 'form-select'}))

    is_coin_to_currency = forms.BooleanField(
        required=False,
        initial=True,  # Set the initial value to True or False
        widget=forms.HiddenInput(attrs={'class': 'form-toggle-input'}),  # Hidden input to store the state
    )


class CurrencyForm(forms.ModelForm):
    class Meta:
        model = Currency
        fields = ['code', 'name']


class CoinForm(forms.ModelForm):
    class Meta:
        model = Coin
        fields = ['name', 'symbol', 'price', 'percentage_change_1h', 'percentage_change_24h', 'percentage_change_7d', 'market_cap', 'all_time_high', 'graph_link', 'icon_url']


class TransactionForm(forms.Form):
    order_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    order_price = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    card_number = forms.CharField(
        label='Card Number',
        max_length=19, min_length=16,
        widget=forms.TextInput(attrs={'pattern': '^[0-9 ]{16,19}$', 'title': 'Card number must be 16 digits'})
    )
    cvv = forms.CharField(
        label='CVV',
        max_length=3,
        widget=forms.TextInput(attrs={'pattern': '[0-9]{3}', 'title': 'CVV must be a 3-digit number'})
    )

    expiry_date = forms.CharField(
        label='Expiry Date',
        required=True,
        widget=forms.TextInput(attrs={'type': 'month'})
    )

    cardholder_name = forms.CharField(
        label='Cardholder Name',
        max_length=250,
        widget=forms.TextInput(attrs={'pattern': '[A-Za-z ]+', 'title': 'Only alphabets and spaces allowed'})
    )

    def __init__(self, coin, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)

        # Set initial values for the fields
        self.initial['order_name'] = coin.name
        self.initial['order_price'] = coin.price

    def clean_card_number(self):
        card_number = ''.join(char for char in self.cleaned_data['card_number'] if char.isdigit())
        if not card_number.isdigit() or len(card_number) != 16:
            raise forms.ValidationError('Invalid card number. It should be a 16-digit number.')
        return card_number

    def clean_cvv(self):
        cvv = self.cleaned_data['cvv']
        if not cvv.isdigit() or len(cvv) != 3:
            raise forms.ValidationError('Invalid CVV. It should be a 3-digit number.')
        return cvv

    def clean_expiry_date(self):
        expiry_date = self.cleaned_data.get('expiry_date')

        # Convert the input string to a date object
        try:
            expiry_date = date.fromisoformat(expiry_date + '-01')  # Assuming day is 01
        except ValueError:
            raise forms.ValidationError('Invalid date format.')

        # Get the current month and year
        current_date = date.today()
        current_month, current_year = current_date.month, current_date.year

        # Check if the selected month and year are greater than or equal to the current month and year
        if expiry_date.year < current_year or (expiry_date.year == current_year and expiry_date.month < current_month):
            raise forms.ValidationError('Expiry date must be greater than or equal to the current month and year.')

        return expiry_date


class BeetForm(forms.ModelForm):
    body = forms.CharField(required=True,
                               widget=forms.widgets.Textarea(
                                   attrs={"placeholder": "What are you thinking today? ",
                                          "class": "form-control"}
                               ),
                               label="",
                               )

    class Meta:
            model = Beet
            exclude = ("user", "likes",)

class ProfilePicForm(forms.ModelForm):
    profile_image = forms.ImageField(label="Profile Picture")

    class Meta:
        model = Profile
        fields = ('profile_image',)

cryptoApp/templates/cryptoApp/add_coin.html
<!-- templates/add_coin.html -->
{% extends 'cryptoApp/base.html' %}

{% block body_block %}
  <h2>Add New Coin</h2>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Coin</button>
  </form>
{% endblock %}

cryptoApp/templates/cryptoApp/article_detail.html
{% extends 'cryptoApp/base.html' %}
{%block body_block%}
  <h2>{{ article.title }}</h2>
  <p>{{ article.content }}</p>
  <p>Posted by: {{ article.author }} on {{ article.created_at }}</p>
{% endblock %}

cryptoApp/templates/cryptoApp/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Byenance</title>
    <link rel="icon" type="image/x-icon" href="../../static/cryptoApp/assets/only-logo.png">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap">
    <link rel="stylesheet" type="text/css" href="{% static 'cryptoApp/index.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'cryptoApp/styles.css' %}"/>


    <script src="https://kit.fontawesome.com/03df4e3e11.js" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'cryptoApp/cards.css' %}"/>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="../../static/cryptoApp/assets/logo.png" alt="logo image" style="width: 150px">
        </a>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Market</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'converter' %}">Converter</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 's_home' %}">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article_list' %}">Community</a>
                </li>
                <li class="dropdown">
                    <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Get listed
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'submit_crypto' %}">Cryptocurrency</a></li>
                        <li><a class="dropdown-item" href="{% url 'submit_exchange' %}">Exchange</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-content="">
                        <img class="profile-icon" src="{{ user.id_or_photo.url }}" alt="Profile">
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 's_home' %}">Post</a>
                </li>

            {% endif %}
        </ul>
    </div>
</nav>

{% if messages %}
    {% for message in messages %}

        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    {% endfor %}
{% endif %}

<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script src="{% static 'cryptoApp/script/index.js' %}"></script>
<script defer src="https://www.livecoinwatch.com/static/lcw-widget.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var profileIcon = document.querySelector('.profile-icon');
        var popover = new bootstrap.Popover(profileIcon, {
            html: true,
            content: getProfilePopoverContent(),
        });

        document.addEventListener('click', function (event) {
            var isInsidePopover = profileIcon.contains(event.target) || event.target.closest('.popover');

            if (!isInsidePopover) {
                popover.hide();
            }
        });
    });

    function getProfilePopoverContent() {
        var name = "{{ user.get_full_name }}";
        var email = "{{ user.email }}";
        var profilePictureUrl = "{{ user.id_or_photo.url }}";

        var content = `
        <div class="profile-popover">
            <img src="${profilePictureUrl}" alt="Profile Picture" class="profile-picture">
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <a href="{% url 'logout_view' %}" class="btn btn-danger logout-button">Logout</a>
        </div>
    `;

        return content;
    }
</script>

</body>
</html>

cryptoApp/templates/cryptoApp/coinDetail.html
{% extends 'cryptoApp/base.html' %}

{% block body_block %}
    <iframe src="https://en.wikipedia.org/wiki/Bitcoin" width="100%" height="100%"></iframe>
{% endblock %}

cryptoApp/templates/cryptoApp/converter.html
{% extends 'cryptoApp/base.html' %}
{% load static %}

{%block body_block%}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Crypto Converter</title>
        <link rel="stylesheet" type="text/css" href="{% static 'cryptoApp/converter.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'cryptoApp/index.css'%}" />
    </head>
    <body>
        <div class="converter-container">
            <h2>CryptoExchange Master</h2>
            <form class="converter-form-container" method="post" action="{% url 'converter' %}" id="converter-form">
                {% csrf_token %}
                <div class="form-input-container">
                    {{ form.amount }}
                </div>

                <div class="form-select-container">
                    {{ form.coin_type }}
                    <input type="hidden" name="{{ form.is_coin_to_currency.name }}"
                           id="{{ form.is_coin_to_currency.id_for_label }}"
                           value="{{ form.is_coin_to_currency.value }}"
                    >
                    <div class="toggle-button" id="toggle-button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="white" class="bi bi-arrow-left-right" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M1 11.5a.5.5 0 0 0 .5.5h11.793l-3.147 3.146a.5.5 0 0 0 .708.708l4-4a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 11H1.5a.5.5 0 0 0-.5.5zm14-7a.5.5 0 0 1-.5.5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H14.5a.5.5 0 0 1 .5.5z"></path>
                        </svg>
                    </div>
                    {{ form.currency }}
                </div>
                <div id="result-container">
                    {% if result %}
                        <div class="result">Result: {{ result }}</div>
                    {% endif %}
                </div>
                <div class="submit-btn">
                    <button class="form-submit" form="converter-form" type="submit" value="button">Convert</button>
                </div>


            </form>
        </div>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#toggle-button').click(function () {
                // Toggle the value of the hidden input field
                let checkbox = $('#id_is_coin_to_currency');
                checkbox.val(checkbox.val() === 'True' ? 'False' : 'True');

                // Submit the form
                $('#converter-form').submit();

                // Update the appearance of the toggle button
                updateToggleFields();
            });

            // Function to update the appearance of the toggle button based on the initial state
            function updateToggleFields() {
                let checkbox = $('#id_is_coin_to_currency');
                let formContainer = $('.form-select-container');

                if (checkbox.val() === 'False') {
                    formContainer.addClass('switch');
                } else {
                    formContainer.removeClass('switch');
                }
            }

            // Initialize the appearance of the toggle button
            updateToggleFields();
        });
    </script>
    </body>
    </html>
{% endblock %}

cryptoApp/templates/cryptoApp/create_article.html
{% extends 'cryptoApp/base.html' %}

{%block body_block%}
  <h2>Create Article</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

cryptoApp/templates/cryptoApp/login.html
{% extends 'cryptoApp/base.html' %}
{% load static %}

{% block body_block %}
    <div class="login-container">
        <div class="login-form-container">
            <h2 class="login-heading">Login to your Account</h2>
            {% if messages %}
                <ul class="alert alert-danger">
                    {% for message in messages %}
                        <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                    {% endfor %}
                </ul>
            {% endif %}
            <form method="post" class="login-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">Username:</label>
                    <br>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">Password:</label>
                    <br>
                    {{ form.password }}
                </div>
                <button type="submit" class="login-page-button">Login</button>
            </form>
            <p class="login-link">Don't have an account? <a href="{% url 'signup' %}" class="login-button" >Sign up</a></p>
        </div>
        <div class="crypto-container">
            <div class="login-text-container">
                <h1 class="login-heading">Get rewards on your crypto with Byenance</h1>
                <p class="login-subtext">
                    Log in and Elevate Your Digital Fortune!</p>
            </div>
            <div class="crypto-image-container">
                <img src="{% static 'cryptoApp/images/loginpageimg.svg' %}" alt="Crypto Image">
            </div>
        </div>
    </div>
{% endblock %}

cryptoApp/templates/cryptoApp/logout.html
{% extends 'cryptoApp/base.html' %}

{% block body_block %}
<h2>You have been logged out successfully.</h2>
  <p><a href="{% url 'login' %}">Login again</a></p>
{% endblock %}

cryptoApp/templates/cryptoApp/payment.html
{% extends 'cryptoApp/base.html' %}
{% load static %}

{% block body_block %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Crypto Converter</title>
        <link rel="stylesheet" type="text/css" href="{% static 'cryptoApp/payment.css' %}">

    </head>
    <body>


<div class="mycustomform">
    <form method="post" action="{% url 'wallet_view' coin.id %}" class="fc1">
        {% csrf_token %}
        <div class="left-column">
            <label for="id_order_name">Order Name:</label>
            {{ form.order_name }}

            <label for="id_order_price">Order Price:</label>
            {{ form.order_price }}
        </div>

        <div class="right-column">
            <label for="id_card_number">Card Number:</label>
            {{ form.card_number }}
            {{ form.card_number.errors }}

        <label for="id_cardholder_name">Cardholder Name:</label>
            {{ form.cardholder_name }}
            {{ form.cardholder_name.errors }}

            <label for="id_expiry_date">Expiry Date:</label>
        {{ form.expiry_date }}
        {{ form.expiry_date.errors }}

            <label for="id_cvv">CVV:</label>
                    {{ form.cvv }}
                    {{ form.cvv.errors }}
            <button type="submit">Submit</button>
        </div>
    </form>
</div>
    </body>
{% endblock %}

cryptoApp/templates/cryptoApp/paymentfailure.html
{% extends 'cryptoApp/base.html' %}

{% load static %}
<!-- success_page.html -->


{% block body_block %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'cryptoApp/payment.css' %}">

    </head>
    <body>
    <div class="success-page-container">
    <div class="success-container">
        <div class="cross-container">
            <div class="cross-mark">&#10006;</div>
            <div class="circle1"></div>
        </div><br>
        <div class="failuremessage">Transaction could not be completed at the moment! Retry again after some time.</div>
    </div>
    </div>

    <footer class="footer mt-auto">
      <div class="container">
       <p>&copy; 2023 Byenance</p>
        <p>
          <a href="{% url 'user_transactions' %}">Check Transaction History</a> |
          <a href="{% url 'index' %}">Go Back to Main Page</a>
        </p>
      </div>
    </footer>
    </body>
{% endblock %}